name: Deploy to Cloudflare R2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check & Install AWS CLI v2
        run: |
          if command -v aws &> /dev/null; then
            echo "✅ AWS CLI is already installed."
            aws --version
          else
            echo "⚠️ AWS CLI not found. Installing..."
            sudo apt-get update
            sudo apt-get install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            echo "✅ AWS CLI Installed."
            aws --version
          fi

      - name: Configure AWS CLI for Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region auto
          aws configure set default.s3.disable_checksum true  # Critical for R2

      - name: Sync to R2
        env:
          R2_ENDPOINT: "https://10b40fbca04e71248a28937609c09a4f.r2.cloudflarestorage.com"
          BUCKET_NAME: radiantrays
          AWS_MAX_ATTEMPTS: 10                # Increased retries
          AWS_S3_MULTIPART_CHUNK_SIZE: 64MB
        run: |
          # Upload non-GLB files first
          aws --endpoint-url "$R2_ENDPOINT" s3 sync ./assets s3://$BUCKET_NAME \
            --exclude "*.glb" \
            --delete \
            --cli-read-timeout 6000

          # Upload GLB files individually with delays
          for file in ./assets/*.glb; do
            aws --endpoint-url "$R2_ENDPOINT" s3 cp "$file" s3://$BUCKET_NAME/ \
              --cli-read-timeout 6000
            sleep 1  # Add delay
          done